default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USER')     { postgres } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { postgres } %>
  host:     <%= ENV.fetch('DATABASE_HOST')     { localhost } %>
  port:     <%= ENV.fetch('DATABASE_PORT')     { 5432 } %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { product_list_developmet } %>

test:
  <<: *default
  database: product_list_test

production:
  <<: *default
  database: control_payments_production
  username: control_payments
  password: <%= ENV['CONTROL_PAYMENTS_DATABASE_PASSWORD'] %>
